### ISSUE TITLE
Portable-VirtualBox 7.1.x (Test Build) observations

### ISSUE THREAD

**Issue by alphastar868** [vboxme/Portable-VirtualBox#99]
**TL;DR**

The [7.1.6 Changelog](https://forum.virtualbox.org/wiki/Changelog-7.1) seems to suggest that there are [still some issue(s) with Win11 guests](https://forums.virtualbox.org/viewtopic.php?t=109352), so I decided to try a [Test Build](https://www.virtualbox.org/wiki/Testbuilds) with **Virtualbox 7.1.7.167852** and **Portable-VirtualBox**.

**Notes**

After installing the rollback edition (Portable-Virtualbox 7.0.12.2 and Win11 Oct'24 ISO (OS Build: 26100.1742), started getting: 

- BugCheck 5c {110, 5250631, 14, ffffffffc0000001} similar to [this](https://forums.virtualbox.org/viewtopic.php?p=491179) and [this](https://forums.virtualbox.org/viewtopic.php?t=113143)
- Guest Additions capability report: (0x0 -> 0x0) seamless: no, hostWindowMapping: no, graphics: no like [this](https://forums.virtualbox.org/viewtopic.php?t=77347)

.. along with some error that indicates that the VM appears to be no longer responding.

I tried this, thinking that it was related to Processor or Acceleration settings or potentially Hyper-V - like [here](https://forums.virtualbox.org/viewtopic.php?t=112538&start=30).

**VBox 7.1 Security Change?**

After upgrading Portable-VirtualBox to 7.1.x release, I started getting errors stating that VBoxSrv is not a member of the TrustedInstaller group.  (I then copied my new 7.1.7.x Portable-VirtualBox7 folder to C:\Program Files\Oracle\ to bypass).  

**Bug? - Portable-VirtualBox builds delete the Portable .EXE**

Also, it seems that using the following sequence causes Portable-Virtualbox7.exe to get deleted from the Portable-VirtualBox7 folder (after build.bat  custom version of Portable-VirtualBox7_v7.1.7.167776 and 7.1.7.167852):

1. Run build.bat to build Portable-VirtualBox using Test Build 7.1.7.167852 per [BUILDING.md](https://github.com/SpruceGuy7/Portable-VirtualBox7/blob/master/BUILDING.md)
2. Run extracted Portable-VirtualBox7.exe file
3. Click Download button
4. Select Extract 64-bit and Run after extraction (optional)
5. Portable-VirtualBox7.exe is deleted, but Virtualbox.exe and folders exist (wrong file gets deleted?)

I simply re-ran my Portable-VirtualBox7 build .exe to re-extract the .exe again.

**Good News**

While 7.1.7.167776 seemed to have issues with rebooting Win11 guests (i.e. high vCPU at 100% and frozen vDisplay - manual PowerOff and PowerOn required), but Virtualbox 7.1.7.167852 seems to work fine for me.  Was able to successfully update to KB5052093 (and Windows 11 OS Build: 26100.3323) with multiple successful reboots.

Here's hoping the next VB/Portable-VirtualBox7 release will be Win11-stable/friendly...

Thanks!

**Comment by alphastar868** [comment]
My humble apologies - this Issue refers to the fork [**SpruceGuy7**/Portable-VirtualBox**7**](https://github.com/SpruceGuy7/Portable-VirtualBox7) which is based on this repository but has significant modifications from this codebase.  Please ignore.
